### PR TITLE
JBIDE-25544: Upgrade to Forge 3.8.1.Final

### PR DESCRIPTION
**Pull request by gastaldi**
@nickboldt please review

### CODE REVIEW

**Comment by nickboldt** [comment]
Looks OK. But do you also need to bump up your plugin/feature versions?

**Comment by gastaldi** [comment]
I think you're right, do you have the `mvn` command to do that?

**Comment by gastaldi** [comment]
`mvn -Dtycho.mode=maven org.eclipse.tycho:tycho-versions-plugin:1.0.0:set-version -DnewVersion=2.0.202-SNAPSHOT` ?

**Comment by nickboldt** [comment]
If that's the next version, then that command looks about right. Run it and see what files are changed locally. Then run a local build and see what artifacts are produced under the `site/target/repository/` folders.

**Pull request merged**
