### PR TITLE
JBIDE-22573: Upgrade to Forge 3.2.2.Final

### PR DESCRIPTION
**Pull request by gastaldi**
@alexeykazakov @maxandersen @fbricon please review.
@psrna already ran some tests and gave his OK.

Thank you

### CODE REVIEW

**Comment by alexeykazakov** [comment]
@gastaldi if we include this in the respin we won't have time to test it the final devstudio/jbt bits. If @psrna has tested this PR and is OK to include it and if no objections from Len, then I'm OK too.

**Comment by alexeykazakov** [comment]
Do not forget to update N&N - https://github.com/jbosstools/jbosstools-website/pull/585

**Comment by gastaldi** [comment]
I will once I get confirmation that this PR is good to be merged ;)

**Comment by psrna** [comment]
Hi all, I've run the whole forge integration test suite with no issues found. If decided to include in respin I'll run the automated suite again on final bits to confirm. This does not take too much time. +1 from me.

**Comment by alexeykazakov** [comment]
OK. +1 for merging it to 4.4.0.x then

**Pull request merged**
