### PR TITLE
JBIDE-21390: Upgrades Forge Runtime to 3.0.0.Beta1

### PR DESCRIPTION
**Pull request by gastaldi**
@maxandersen @alexeykazakov @fbricon can you verify this?

### CODE REVIEW

**Comment by fbricon** [comment]
LTGM +1

**Comment by gastaldi** [comment]
What does LTGM stands for? Am I missing something?

**Comment by fbricon** [comment]
typo on Looks Good To Me :-)

**Comment by gastaldi** [comment]
Merged in https://github.com/jbosstools/jbosstools-forge/commit/bf3a216c8252f9ae50ef0169f8b1182582065309

**Pull request closed without merging**
