### PR TITLE
JBIDE-22547: White spaces are now properly replaced

### PR DESCRIPTION
**Pull request by gastaldi**
@alexeykazakov @maxandersen @fbricon please review

### CODE REVIEW

**Comment by alexeykazakov** [comment]
Any tests?

**Comment by gastaldi** [comment]
Hm no, but I give you my word it works :)

**Comment by alexeykazakov** [comment]
I trust you it works but tests are not about making sure the fix works. It's about making sure the code still works when you change something else next time ;)

**Comment by gastaldi** [comment]
Closing PR as it's origin is master

**Pull request closed without merging**
