### PR TITLE
JBIDE-19836 use JUnit 4.12.0 instead of 3.8.2 >> master

### PR DESCRIPTION
**Pull request by nickboldt**

### CODE REVIEW

**Comment by nickboldt** [comment]
You may prefer to se NO version constraint on JUnit use.

**Comment by gastaldi** [comment]
Good idea, will do that

**Comment by gastaldi** [comment]
Merged, thanks!

**Comment by maxandersen** [comment]
if you use Junit 4 features you need to set it to junit 4, not allow junit 3.

**Pull request closed without merging**
