### PR TITLE
JBIDE-19404: Upgrade Forge Runtime to 2.15.0.Final

### PR DESCRIPTION
**Pull request by gastaldi**
These commits are required to support Forge 2.15.0.Final

### CODE REVIEW

**Comment by alexeykazakov** [comment]
Are all these three commits related to the forge upgrade?

**Comment by gastaldi** [comment]
Yes, that is correct. They are the reason why the upgrade is necessary

**Comment by alexeykazakov** [comment]
Looks OK to me. I would squash them though.

**Comment by gastaldi** [comment]
PR merged, thanks!

**Pull request closed without merging**
