### PR TITLE
JBIDE-21179: Upgrades Forge runtime to 3.0.0.Alpha2

### PR DESCRIPTION
**Pull request by gastaldi**
@fbricon @maxandersen @alexeykazakov can anyone review this?

### CODE REVIEW

**Comment by alexeykazakov** [comment]
Looks good to me if you think we should migrate Mars users to Forge 3.0.0.Alpha2 too.

**Comment by gastaldi** [comment]
Yes, I think we should. The sooner the better. People are already using it in netbeans and intellij.

**Comment by alexeykazakov** [comment]
+1

**Comment by gastaldi** [comment]
Thanks!

**Comment by maxandersen** [comment]
guys - doesn't Forge *break* users ? 

How about the angularJS Forge wizard/cheatsheet ?  is it aligned withthis?

**Pull request merged**
