### PR TITLE
JBIDE-21791: Prompt user to save open current open editor before executing command

### PR DESCRIPTION
**Pull request by gastaldi**
@fbricon @maxandersen @alexeykazakov can someone review this?

### CODE REVIEW

**Comment by alexeykazakov** [comment]
https://issues.jboss.org/browse/JBIDE-21791?focusedCommentId=13173827&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13173827

**Comment by gastaldi** [comment]
This is how the save dialog is displayed. I used `org.eclipse.ui.IWorkbenchPage.saveEditor(IEditorPart, boolean)` with the boolean part being picked from the preferences page.  How can I add a "Don't ask again" checkbox on it? 
screenshot from 2016-03-08 17-30-20

**Comment by gastaldi** [comment]
This is the preferences page.
screenshot from 2016-03-08 17-34-38

**Comment by gastaldi** [comment]
This is how the preferences page is now

screenshot from 2016-03-08 17-51-48

**Comment by gastaldi** [comment]
Confirmation dialog: 
screenshot from 2016-03-08 19-47-10

Preferences Page:
screenshot from 2016-03-08 19-45-19

**Comment by maxandersen** [comment]
Looks good (just looking at UI) 

Suggestion for reword: "(For Forge to access latest changes you need to save)"

**Comment by gastaldi** [comment]
Done, thanks for the rewording hint

**Pull request merged**
