### PR TITLE
JBIDE-22184: Upgraded to Forge 3.1.0.Final

### PR DESCRIPTION
**Pull request by gastaldi**
@alexeykazakov @fbricon @maxandersen can you review?

### CODE REVIEW

**Comment by fbricon** [comment]
mmm that ship (4.3.x)  has sailed I think. 4.4 is the new 4.3

**Comment by gastaldi** [comment]
So master branch then?

**Comment by fbricon** [comment]
@gastaldi yes, unless @maxandersen, @nickboldt, @alexeykazakov are willing to do another respin right before we ship 4.3.1, which I strongly doubt.

What does Forge 3.1.0.Final bring? does it fix critical/blocker bugs?

**Comment by gastaldi** [comment]
No blockers. Just minor fixes. It's a minor update because introduces some
minor API changes and new features.
Em 15/04/2016 13:41, "Fred Bricon" <notifications@github.com> escreveu:

**Comment by gastaldi** [comment]
Closing PR

**Comment by alexeykazakov** [comment]
To late for JBDS 9.1.0, JBT 4.3.1.
So yes, go for master.

**Pull request closed without merging**
