### PR TITLE
Introduce GitHub Actions workflow for PR check, fixes JBIDE-27699

### PR DESCRIPTION
**Pull request by odockal**

### CODE REVIEW

**Comment by odockal** [comment]
@sbouchet Take a look please

**Review by sbouchet — APPROVED** [review]
LGTM.

**Comment by odockal** [comment]
@sbouchet  I do not have merge rights here.

**Comment by sbouchet** [comment]
> @sbouchet I do not have merge rights here.

and also notright to add me as reviewer ?

**Pull request merged**
