### PR TITLE
JBIDE-21179: Upgrades Forge runtime to 3.0.0.Alpha3

### PR DESCRIPTION
**Pull request by gastaldi**
This fixes an issue the Fuse team was having with their addons.

@alexeykazakov @maxandersen @fbricon can you verify it?

### CODE REVIEW

**Comment by alexeykazakov** [comment]
+1.
So the Fuse team is OK to update to 3.0.0?

**Comment by gastaldi** [comment]
Yes, here is  the chat I had with @davclaus about it: http://transcripts.jboss.org/channel/irc.freenode.org/%23forge/2015/%23forge.2015-12-09.log.html

**Comment by maxandersen** [comment]
Is @davclaus aware that Fuse IDE is still targeting Eclipse Kepler and thus not going to have Fuse 3.0 for a long time ?

**Comment by davsclaus** [comment]
@maxandersen the Fuse IDE is different tool than what we do upstream at fabric8. We just need jboss forge in eclipse. And we will target for forge 3.0 onwards.

**Comment by davsclaus** [comment]
and its currently upstream only, not part of a redhat product etc. so its fine to only run on the latest eclipse version.

**Comment by maxandersen** [comment]
@davsclaus I thought there was camel forge tooling used in Fuse product - so that is not true ?

**Comment by davsclaus** [comment]
No Fuse IDE do not use any of the fabric8 code.

However I hope that they will reuse that in the future, we do now have some tooling that can edit endpoints in Java routes. And more to come with small wizards to setup ActiveMQ, and other components etc.

So ideally Fuse IDE could bring some of these commands in in a future release, or reuse the logic but do nicer graphical UI in pure Eclipse way.

Though Fuse IDE and the Camel forge tools reuse the same camel-catalog from Apache Camel, that contains all the needed metadata about Camel, so we both know exactly which components there are, what options they have, and all their types, enums, documentation and so on.

**Pull request merged**
